import './jquery.cookie'
import './bjui-core'
import './bjui-regional.zh-CN'
import './bjui-frag'

import './Tools/_index'

import './bjui-extends'
import './bjui-modulefixed'

import './Plugins/_index'

import './bjui-basedrag'
import './bjui-layout'
import './bjui-contextmenu'
import './bjui-navtab'
import './bjui-dialog'
import './bjui-taskbar'
import './bjui-ajax'
import './bjui-alertmsg'
import './bjui-pagination'
import './bjui-ajaxtab'
import './bjui-tablefixed'
import './bjui-tabledit'
import './bjui-spinner'
import './bjui-lookup'
import './bjui-upload'
import './bjui-initui'
import './bjui-plugins'
