
import './js/jquery.cookie.js'
import './js/bjui-core.js'
import './js/bjui-regional.zh-CN.js'
import './js/bjui-frag.js'
import './js/bjui-extends.js'
import './js/bjui-modulefixed.js'
import './js/bjui-basedrag.js'
import './js/bjui-sidebar.js'
import './js/bjui-contextmenu.js'
import './js/bjui-navtab.js'
import './js/bjui-dialog.js'
import './js/bjui-taskbar.js'
import './js/bjui-ajax.js'
import './js/bjui-alertmsg.js'
import './js/bjui-pagination.js'
import './js/bjui-datepicker.js'
import './js/bjui-ajaxtab.js'
import './js/bjui-tablefixed.js'
import './js/bjui-tabledit.js'
import './js/bjui-spinner.js'
import './js/bjui-lookup.js'
import './js/bjui-upload.js'
import './js/bjui-theme.js'
import './js/bjui-initui.js'
import './js/bjui-plugins.js'

import './js/plugins/jquery.validator.theme'
